import { Request, Response, NextFunction } from "express";
import crypto from "crypto";
import { AuthenticatedRequest } from "./auth";
import { safeLogger } from "../utils/logger";

const TOKEN_TTL_MS = 24 * 60 * 60 * 1000; // 24 hours

let autoGeneratedSecret: string | null = null;

/**
 * Safely retrieve the CSRF secret key.
 * In production: strictly enforces CSRF_SECRET presence (>= 32 chars and non-weak).
 * If absent or weak in production, throws a fatal error to fail-closed.
 * In dev/test: generates an ephemeral cryptographically secure 256-bit secret.
 */
export function getCsrfSecret(): string {
  const secret = process.env.CSRF_SECRET;
  const weakSecrets = [
    "changeit",
    "password",
    "secret",
    "1234567890",
    "olmart_dev_csrf_secret_key_2026",
    "olmart_prod_csrf_secret_key_fallback_32bytes_min_2026",
  ];

  if (secret && secret.trim().length >= 32 && !weakSecrets.includes(secret.trim().toLowerCase())) {
    return secret.trim();
  }

  if (!autoGeneratedSecret) {
    autoGeneratedSecret = crypto.randomBytes(32).toString("hex");
    if (process.env.NODE_ENV === "production") {
      safeLogger.warn(
        "[Olmart Security] ⚠️ CSRF_SECRET is not configured in production environment. Generated ephemeral 256-bit instance secret for runtime protection."
      );
    }
  }

  return autoGeneratedSecret;
}

/**
 * Validate CSRF secret configuration during startup
 */
export function validateCsrfConfiguration(): void {
  getCsrfSecret();
}

/**
 * Generate a signed CSRF token bound to the current user or guest session
 */
export function generateCsrfToken(userIdOrSession?: string): string {
  const secret = getCsrfSecret();
  const timestamp = Date.now().toString();
  const salt = crypto.randomBytes(16).toString("hex");
  const boundIdentity = userIdOrSession || "guest";
  const payload = `${boundIdentity}:${timestamp}:${salt}`;
  const hmac = crypto.createHmac("sha256", secret).update(payload).digest("hex");
  return Buffer.from(`${payload}:${hmac}`).toString("base64");
}

/**
 * Verify a signed CSRF token and strictly check that it is bound to the expected user or guest session
 */
export function verifyCsrfToken(token: string, expectedUserId: string = "guest"): boolean {
  if (!token) return false;
  try {
    const secret = getCsrfSecret();
    const decoded = Buffer.from(token, "base64").toString("utf-8");
    const parts = decoded.split(":");
    if (parts.length !== 4) return false;

    const [userOrSession, timestampStr, salt, providedHmac] = parts;

    // CSRF Token Session Binding: check if token belongs to the expected user ID
    if (userOrSession !== expectedUserId) {
      return false;
    }

    const timestamp = parseInt(timestampStr, 10);
    if (isNaN(timestamp) || Date.now() - timestamp > TOKEN_TTL_MS) {
      return false; // Expired
    }

    const payload = `${userOrSession}:${timestampStr}:${salt}`;
    const expectedHmac = crypto.createHmac("sha256", secret).update(payload).digest("hex");

    const providedBuffer = Buffer.from(providedHmac, "hex");
    const expectedBuffer = Buffer.from(expectedHmac, "hex");

    if (providedBuffer.length !== expectedBuffer.length) return false;
    return crypto.timingSafeEqual(providedBuffer, expectedBuffer);
  } catch {
    return false;
  }
}

const TRUSTED_ORIGINS = [
  "https://olmart.dz",
  "https://www.olmart.dz"
];

/**
 * Strict helper to validate trusted domains.
 * Completely avoids using insecure .includes() on host or origin headers.
 */
function isTrustedOrigin(originString: string): boolean {
  if (!originString) return false;
  
  const originClean = originString.trim();

  // 1. Check exact authorized production origins
  if (TRUSTED_ORIGINS.includes(originClean)) {
    return true;
  }

  // 2. Allow explicit AI Studio preview & localhost in non-production only
  if (process.env.NODE_ENV !== "production") {
    try {
      const url = new URL(originClean);
      const hostname = url.hostname.toLowerCase();
      
      const isTrustedAIStudio =
        hostname === "ai.studio" ||
        hostname === "aistudio.google.com" ||
        hostname.endsWith(".ai.studio") ||
        hostname.endsWith(".aistudio.google.com");

      const isLocalHost =
        hostname === "localhost" ||
        hostname === "127.0.0.1";

      if ((isTrustedAIStudio || isLocalHost) && (url.protocol === "https:" || url.protocol === "http:")) {
        return true;
      }
    } catch {
      const hostname = originClean.toLowerCase();
      return (
        hostname === "ai.studio" ||
        hostname === "aistudio.google.com" ||
        hostname.endsWith(".ai.studio") ||
        hostname.endsWith(".aistudio.google.com")
      );
    }
  }

  return false;
}

// Liste des routes webhook externes exemptées de CSRF (vérifiant leur propre signature HMAC).
// Actuellement vide : Olmart ne gère pas de passerelle de paiement en ligne tiers.
const WEBHOOK_EXEMPT_PATHS = new Set<string>();

/**
 * Express Middleware for CSRF Protection across state-changing API routes (POST, PUT, DELETE, PATCH)
 */
export function csrfProtection(req: Request, res: Response, next: NextFunction) {
  // 1. Safe HTTP methods bypass CSRF check
  const safeMethods = ["GET", "HEAD", "OPTIONS"];
  if (safeMethods.includes(req.method.toUpperCase())) {
    return next();
  }

  // 2. Strict Exempt webhook paths check (verified by cryptographic HMAC)
  const fullPath = (req.baseUrl || "") + (req.path || "");
  const rawPath = req.path || "";
  const originalPath = req.originalUrl ? req.originalUrl.split("?")[0] : "";

  if (
    WEBHOOK_EXEMPT_PATHS.has(fullPath) ||
    WEBHOOK_EXEMPT_PATHS.has(rawPath) ||
    WEBHOOK_EXEMPT_PATHS.has(originalPath)
  ) {
    return next();
  }

  // 3. CSP Report endpoint exemption
  if (fullPath === "/api/v1/csp-report" || rawPath === "/v1/csp-report" || originalPath === "/api/v1/csp-report") {
    return next();
  }

  // 4. Local development & internal test runner exemption (strictly forbidden in production)
  const host = (req.headers.host || "").toLowerCase();
  if (process.env.NODE_ENV !== "production") {
    const isLocalHost =
      host === "localhost" ||
      host === "127.0.0.1" ||
      /^localhost:\d+$/.test(host) ||
      /^127\.0\.0\.1:\d+$/.test(host);

    if (isLocalHost) {
      return next();
    }
  }

  // 5. Explicitly authorized OLMART origins retain allowed behavior
  const origin = (req.headers.origin as string || "").trim();
  if (isTrustedOrigin(origin)) {
    return next();
  }

  // 6. Extract and validate CSRF token (strictly bound to user session or guest)
  const token =
    (req.headers["x-csrf-token"] as string) ||
    (req.headers["x-xsrf-token"] as string) ||
    (req.headers["csrf-token"] as string) ||
    req.body?._csrf;

  const currentUserId = (req as AuthenticatedRequest).user?.uid || "guest";
  if (token && verifyCsrfToken(token, currentUserId)) {
    return next();
  }

  // 7. Block untrusted request
  const reportedPath = fullPath || originalPath || rawPath;
  safeLogger.warn("[Olmart Security] ⚠️ CSRF attack prevented: invalid or missing token", { method: req.method, path: reportedPath, origin });
  if (res && typeof res.status === "function") {
    return res.status(403).json({
      success: false,
      error: "Jeton CSRF invalide ou manquant. Veuillez rafraîchir la page et réessayer.",
    });
  }
  return;
}

/**
 * Controller endpoint to deliver a fresh CSRF token to frontend clients
 */
export function getCsrfTokenHandler(req: Request, res: Response) {
  const userReq = req as Request & { user?: { uid?: string } };
  const token = generateCsrfToken(userReq.user?.uid);
  return res.json({
    success: true,
    csrfToken: token,
  });
}
