import { compressAndResizeImage, CompressResult, DbBanner, TagType } from "./bannerAdmin/useBannerTypes";
import { useBannerCrud } from "./bannerAdmin/useBannerCrud";
import { useBannerOrdering } from "./bannerAdmin/useBannerOrdering";
import { useBannerWilayaCampaigns } from "./bannerAdmin/useBannerWilayaCampaigns";
import { useBannerModal } from "./bannerAdmin/useBannerModal";

export type { DbBanner, TagType, CompressResult };
export { compressAndResizeImage as compressAndResize };

export function useBannerAdmin() {
  const crud = useBannerCrud();

  const modal = useBannerModal(crud.banners, crud.fetchData);

  const ordering = useBannerOrdering(crud.banners, crud.setBanners, crud.fetchData);

  const wilaya = useBannerWilayaCampaigns(
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "#F5F6F8",
    "#111111",
    "",
    "",
    "",
    "",
    "#111111",
    "#FFFFFF"
  );

  return {
    banners: crud.banners,
    tags: crud.tags,
    allProducts: crud.allProducts,
    isLoading: crud.isLoading,
    activeTab: modal.activeTab,
    setActiveTab: modal.setActiveTab,
    selectedZone: modal.selectedZone,
    setSelectedZone: modal.setSelectedZone,
    isModalOpen: modal.isModalOpen,
    setIsModalOpen: modal.setIsModalOpen,
    isSubmitting: modal.isSubmitting,
    editingBanner: modal.editingBanner,
    title: modal.title,
    setTitle: modal.setTitle,
    titleColor: modal.titleColor,
    setTitleColor: modal.setTitleColor,
    subtitle: modal.subtitle,
    setSubtitle: modal.setSubtitle,
    subtitleColor: modal.subtitleColor,
    setSubtitleColor: modal.subtitleColor,
    buttonText: modal.buttonText,
    setButtonText: modal.setButtonText,
    btnBgColor: modal.btnBgColor,
    setBtnBgColor: modal.setBtnBgColor,
    btnTextColor: modal.btnTextColor,
    setBtnTextColor: modal.setBtnTextColor,
    desktopImage: modal.desktopImage,
    setDesktopImage: modal.setDesktopImage,
    mobileImage: modal.mobileImage,
    setMobileImage: modal.setMobileImage,
    tagId: modal.tagId,
    setTagId: modal.setTagId,
    sortOrder: modal.sortOrder,
    setSortOrder: modal.setSortOrder,
    isActive: modal.isActive,
    setIsActive: modal.setIsActive,
    startDate: modal.startDate,
    setStartDate: modal.setStartDate,
    endDate: modal.endDate,
    setEndDate: modal.setEndDate,
    featuredProducts: modal.featuredProducts,
    setFeaturedProducts: modal.setFeaturedProducts,
    abGroup: modal.abGroup,
    setAbGroup: modal.setAbGroup,
    isPreviewModalOpen: modal.isPreviewModalOpen,
    setIsPreviewModalOpen: modal.setIsPreviewModalOpen,
    previewBannerData: modal.previewBannerData,
    setPreviewBannerData: modal.setPreviewBannerData,
    tagName: crud.tagName,
    setTagName: crud.setTagName,
    tagSlug: crud.tagSlug,
    setTagSlug: crud.setTagSlug,
    draggedIndex: ordering.draggedIndex,
    isUploadingDesktop: modal.isUploadingDesktop,
    uploadProgressDesktop: modal.uploadProgressDesktop,
    isUploadingMobile: modal.isUploadingMobile,
    uploadProgressMobile: modal.uploadProgressMobile,
    wilayaCampaigns: wilaya.wilayaCampaigns,
    selectedWilayaToEdit: wilaya.selectedWilayaToEdit,
    setSelectedWilayaToEdit: wilaya.setSelectedWilayaToEdit,
    hasWilayaCampaign: wilaya.hasWilayaCampaign,
    setHasWilayaCampaign: wilaya.setHasWilayaCampaign,
    wilayaHeroTitle: wilaya.wilayaHeroTitle,
    setWilayaHeroTitle: wilaya.setWilayaHeroTitle,
    wilayaHeroSubtitle: wilaya.wilayaHeroSubtitle,
    setWilayaHeroSubtitle: wilaya.setWilayaHeroSubtitle,
    wilayaHeroImage: wilaya.wilayaHeroImage,
    setWilayaHeroImage: wilaya.setWilayaHeroImage,
    wilayaPromoLeftTitle: wilaya.wilayaPromoLeftTitle,
    setWilayaPromoLeftTitle: wilaya.setWilayaPromoLeftTitle,
    wilayaPromoLeftBadge: wilaya.wilayaPromoLeftBadge,
    setWilayaPromoLeftBadge: wilaya.setWilayaPromoLeftBadge,
    wilayaPromoLeftCtaLink: wilaya.wilayaPromoLeftCtaLink,
    setWilayaPromoLeftCtaLink: wilaya.setWilayaPromoLeftCtaLink,
    wilayaPromoLeftImage: wilaya.wilayaPromoLeftImage,
    setWilayaPromoLeftImage: wilaya.setWilayaPromoLeftImage,
    wilayaPromoLeftBgColor: wilaya.wilayaPromoLeftBgColor,
    setWilayaPromoLeftBgColor: wilaya.setWilayaPromoLeftBgColor,
    wilayaPromoLeftTextColor: wilaya.wilayaPromoLeftTextColor,
    setWilayaPromoLeftTextColor: wilaya.setWilayaPromoLeftTextColor,
    wilayaPromoRightTitle: wilaya.wilayaPromoRightTitle,
    setWilayaPromoRightTitle: wilaya.setWilayaPromoRightTitle,
    wilayaPromoRightBadge: wilaya.wilayaPromoRightBadge,
    setWilayaPromoRightBadge: wilaya.setWilayaPromoRightBadge,
    wilayaPromoRightCtaLink: wilaya.wilayaPromoRightCtaLink,
    setWilayaPromoRightCtaLink: wilaya.setWilayaPromoRightCtaLink,
    wilayaPromoRightImage: wilaya.wilayaPromoRightImage,
    setWilayaPromoRightImage: wilaya.setWilayaPromoRightImage,
    wilayaPromoRightBgColor: wilaya.wilayaPromoRightBgColor,
    setWilayaPromoRightBgColor: wilaya.setWilayaPromoRightBgColor,
    wilayaPromoRightTextColor: wilaya.wilayaPromoRightTextColor,
    setWilayaPromoRightTextColor: wilaya.setWilayaPromoRightTextColor,
    isUploadingWilayaHero: wilaya.isUploadingWilayaHero,
    uploadProgressWilayaHero: wilaya.uploadProgressWilayaHero,
    isUploadingWilayaPromoLeft: wilaya.isUploadingWilayaPromoLeft,
    uploadProgressWilayaPromoLeft: wilaya.uploadProgressWilayaPromoLeft,
    isUploadingWilayaPromoRight: wilaya.isUploadingWilayaPromoRight,
    uploadProgressWilayaPromoRight: wilaya.uploadProgressWilayaPromoRight,
    handleTagNameChange: crud.handleTagNameChange,
    handleCreateTag: crud.handleCreateTag,
    handleDeleteTag: crud.handleDeleteTag,
    handleDeleteBanner: crud.handleDeleteBanner,
    handleOpenAddModal: modal.handleOpenAddModal,
    handleEditBanner: modal.handleEditBanner,
    handleSaveBanner: modal.handleSaveBanner,
    handleOpenPreviewModal: modal.handleOpenPreviewModal,
    shiftIndex: ordering.shiftIndex,
    handleDragStart: ordering.handleDragStart,
    handleDragOver: ordering.handleDragOver,
    handleDrop: ordering.handleDrop,
    handleDesktopImageUpload: modal.handleDesktopImageUpload,
    handleMobileImageUpload: modal.handleMobileImageUpload,
    handleWilayaHeroImageUpload: wilaya.handleWilayaHeroImageUpload,
    handleWilayaPromoLeftImageUpload: wilaya.handleWilayaPromoLeftImageUpload,
    handleWilayaPromoRightImageUpload: wilaya.handleWilayaPromoRightImageUpload,

    // Aliases required by BannerAdmin.tsx & BannerFormModalProps
    isBannerModalOpen: modal.isModalOpen,
    setIsBannerModalOpen: modal.setIsModalOpen,
    selectedBanner: modal.editingBanner,
    bannerTitle: modal.title,
    setBannerTitle: modal.setTitle,
    bannerTitleColor: modal.titleColor,
    setBannerTitleColor: modal.setTitleColor,
    bannerSubtitle: modal.subtitle,
    setBannerSubtitle: modal.setSubtitle,
    bannerSubtitleColor: modal.subtitleColor,
    setBannerSubtitleColor: modal.setSubtitleColor,
    bannerButtonText: modal.buttonText,
    setBannerButtonText: modal.setButtonText,
    bannerBtnBgColor: modal.btnBgColor,
    setBannerBtnBgColor: modal.setBtnBgColor,
    bannerBtnTextColor: modal.btnTextColor,
    setBannerBtnTextColor: modal.setBtnTextColor,
    bannerDesktopImage: modal.desktopImage,
    setBannerDesktopImage: modal.setDesktopImage,
    bannerMobileImage: modal.mobileImage,
    setBannerMobileImage: modal.setMobileImage,
    bannerTagId: modal.tagId,
    setBannerTagId: modal.setTagId,
    bannerIsActive: modal.isActive,
    setBannerIsActive: modal.setIsActive,
    bannerFeaturedProducts: modal.featuredProducts,
    setBannerFeaturedProducts: modal.setFeaturedProducts,
    bannerTargetUserType: modal.targetUserType,
    setBannerTargetUserType: modal.setTargetUserType,
    bannerTargetRegions: modal.targetRegions,
    setBannerTargetRegions: modal.setTargetRegions,
    bannerStartDate: modal.startDate,
    setBannerStartDate: modal.setStartDate,
    bannerEndDate: modal.endDate,
    setBannerEndDate: modal.setEndDate,
    bannerAbGroup: modal.abGroup,
    setBannerAbGroup: modal.setAbGroup,
    bannerZone: modal.selectedZone,
    setBannerZone: modal.setSelectedZone,
    productSearchTerm: modal.productSearchTerm,
    setProductSearchTerm: modal.setProductSearchTerm,
    previewDeviceMode: modal.previewDeviceMode,
    setPreviewDeviceMode: modal.setPreviewDeviceMode,
    handleImageUpload: async (e: React.ChangeEvent<HTMLInputElement>, type: "desktop" | "mobile") => {
      if (type === "desktop") {
        await modal.handleDesktopImageUpload(e);
      } else {
        await modal.handleMobileImageUpload(e);
      }
    },
    handleOpenBannerModal: (banner?: DbBanner | null) => {
      if (banner) {
        modal.handleEditBanner(banner);
      } else {
        modal.handleOpenAddModal();
      }
    },
  };
}
